
export const DENTAL_TERMS = [
  "amoxicillin", "ibuprofen", "metronidazole", "periapical", "endodontic", 
  "periodontal", "occlusal", "mandibular", "maxillary", "bracket", "orthodontic",
  "scaling", "rootplaning", "prophylaxis", "composite", "amalgam", "extraction",
  "impaction", "gingivitis", "periodontitis", "pulpitis", "abscess", "denture",
  "implant", "crown", "bridge", "veneer", "sealant", "fluoride", "anesthesia",
  "lidocaine", "epinephrine", "molar", "premolar", "canine", "incisor", "distal",
  "mesial", "buccal", "lingual", "palatal", "facial", "subgingival", "supragingival",
  "halitosis", "xerostomia", "bruxism", "malocclusion", "overbite", "underbite",
  "crossbite", "cavity", "caries", "decalcification", "enamel", "dentin", "pulp",
  "cementum", "alveolar", "panoramic", "bitewing", "cephalometric", "radiograph",
  "stomatitis", "thrush", "candidiasis", "clindamycin", "cephalexin", "azithromycin",
  "chlorhexidine", "doxycycline", "tetracycline", "vicodin", "percocet", "tramadol",
  "acetaminophen", "naproxen", "ketorolac", "dexamethasone", "prednisone",
  "sulfa", "penicillin", "erythromycin", "miconazole", "nystatin", "acyclovir",
  "valacyclovir", "penciclovir", "triamcinolone", "benzocaine", "articaine",
  "mepivacaine", "bupivacaine", "prilocaine", "septocaine", "carbocaine",
  "marcacine", "novocaine", "nitrous", "diazepam", "lorazepam", "triazolam",
  "midazolam", "hydroxyzine", "promethazine", "clonazepam", "alprazolam",
  "paracetamol", "codeine", "hydrocodone", "oxycodone", "fentanyl", "morphine",
  "celecoxib", "diclofenac", "meloxicam", "indomethacin", "aspirin", "plavix",
  "warfarin", "eliquis", "xarelto", "pradaxa", "aspirin", "clopidogrel",
  "lisinopril", "amlodipine", "metoprolol", "atorvastatin", "metformin",
  "levothyroxine", "albuterol", "gabapentin", "omeprazole", "losartan",
  "sertraline", "escitalopram", "fluoxetine", "citalopram", "trazodone",
  "duloxetine", "venlafaxine", "bupropion", "quetiapine", "aripiprazole",
  "risperidone", "olanzapine", "haloperidol", "lithium", "valproate",
  "lamotrigine", "topiramate", "zonisamide", "levetiracetam", "phenytoin",
  "carbamazepine", "oxcarbazepine", "phenobarbital", "prednisolone",
  "methylprednisolone", "hydrocortisone", "betamethasone", "clobetasol",
  "mometasone", "fluticasone", "budesonide", "tiotropium", "ipratropium",
  "montelukast", "zafirlukast", "theophylline", "roflumilast"
];
